
import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(page_title="QuLab", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab: ML Model Risk Auditing")
st.divider()

# Initialize session state for data if not already present
if "raw_data" not in st.session_state:
    st.session_state.raw_data = None
if "cleaned_data" not in st.session_state:
    st.session_state.cleaned_data = None
if "metadata" not in st.session_state:
    st.session_state.metadata = pd.DataFrame(
        columns=["Attribute", "Description", "Source",
                 "Last Updated", "Provenance Log"]
    )
if "provenance_logs" not in st.session_state:
    st.session_state.provenance_logs = pd.DataFrame(
        columns=["Timestamp", "Action", "Description", "User"]
    )
if "bias_metrics" not in st.session_state:
    st.session_state.bias_metrics = {}
if "current_page" not in st.session_state:
    st.session_state.current_page = "1. Data Ingestion & Overview"

# List of page options
page_options = [
    "1. Data Ingestion & Overview",
    "2. Data Provenance & Metadata Management",
    "3. Data Quality Audits",
    "4. Data Cleaning and Preprocessing",
    "5. Bias Detection & Analysis",
    "6. Risk Simulation & Human Oversight",
    "7. Risk Register & Governance",
    "8. Audit Report & Insights"
]

# Get the index of the current page
current_index = page_options.index(
    st.session_state.current_page) if st.session_state.current_page in page_options else 0

page = st.sidebar.selectbox(
    label="Navigation",
    options=page_options,
    index=current_index,
    key="page_selector"
)

# Update current_page when selectbox changes
if page != st.session_state.current_page:
    st.session_state.current_page = page

if page == "1. Data Ingestion & Overview":
    from application_pages.page_1_data_ingestion import main
    main()
elif page == "2. Data Provenance & Metadata Management":
    from application_pages.page_2_data_provenance import main
    main()
elif page == "3. Data Quality Audits":
    from application_pages.page_3_data_quality_audits import main
    main()
elif page == "4. Data Cleaning and Preprocessing":
    from application_pages.page_4_data_cleaning import main
    main()
elif page == "5. Bias Detection & Analysis":
    from application_pages.page_5_bias_detection import main
    main()
elif page == "6. Risk Simulation & Human Oversight":
    from application_pages.page_6_risk_simulation import main
    main()
elif page == "7. Risk Register & Governance":
    from application_pages.page_7_risk_register import main
    main()
elif page == "8. Audit Report & Insights":
    from application_pages.page_8_audit_report import main
    main()


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@qusandbox.com](mailto:info@qusandbox.com)
''')
